name: Move assigned pull requests into To do

on:
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: test
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN }}
