name: Update GitHub Project

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [opened, reopened, converted_to_draft, ready_for_review]

env:
  PROJECT_NUMBER: 15
  ISSUE_STATUSES: '{"priority-high": "High Priority", "priority-medium": "Medium Priority", "priority-low": "Low Priority", "Epic": "Epics"}'
  PR_STATUS_DRAFT: 'In Progress'
  PR_STATUS_READY: 'Review/QA'

permissions:
  pull-requests: write

jobs:
  update-project:
    name: Move project item
    runs-on: ubuntu-latest
    steps:
    - uses: zowe-actions/shared-actions/project-move-item@main
      if: ${{ github.event.issue && fromJSON(env.ISSUE_STATUSES)[github.event.label.name] }}
      with:
        item-status: ${{ fromJSON(env.ISSUE_STATUSES)[github.event.label.name] }}
        project-number: ${{ env.PROJECT_NUMBER }}
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

    - uses: zowe-actions/shared-actions/project-move-item@main
      if: ${{ github.event.pull_request }}
      with:
        assign-author: true
        item-status: ${{ github.event.action == 'ready_for_review' && env.PR_STATUS_READY || env.PR_STATUS_DRAFT }}
        project-number: ${{ env.PROJECT_NUMBER }}
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
