name: Update GitHub Project

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [opened, reopened, converted_to_draft, ready_for_review]

env:
  PROJECT_NUMBER: 15

jobs:
  update-project:
    name: Move project item
    runs-on: ubuntu-latest
    steps:
    - uses: zowe-actions/shared-actions/project-move-item@actions/project-move-item
      if: ${{ github.event.pull_request }}
      with:
        assign-author: true
        item-status: ${{ github.event.action == 'ready_for_review' && 'Review/QA' || 'In Progress' }}
        project-number: ${{ env.PROJECT_NUMBER }}
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

    - uses: zowe-actions/shared-actions/project-move-item@actions/project-move-item
      if: ${{ github.event.issue && github.event.label.name == 'priority-high' }}
      with:
        item-status: High Priority
        project-number: ${{ env.PROJECT_NUMBER }}
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

    - uses: zowe-actions/shared-actions/project-move-item@actions/project-move-item
      if: ${{ github.event.issue && github.event.label.name == 'priority-medium' }}
      with:
        item-status: Medium Priority
        project-number: ${{ env.PROJECT_NUMBER }}
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

    - uses: zowe-actions/shared-actions/project-move-item@actions/project-move-item
      if: ${{ github.event.issue && github.event.label.name == 'priority-low' }}
      with:
        item-status: Low Priority
        project-number: ${{ env.PROJECT_NUMBER }}
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

    - uses: zowe-actions/shared-actions/project-move-item@actions/project-move-item
      if: ${{ github.event.issue && github.event.label.name == 'Epic' }}
      with:
        item-status: Epics
        project-number: ${{ env.PROJECT_NUMBER }}
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
