name: Zowe Explorer Samples CI

on:
  push:
    paths:
      - .github/workflows/zowe-explorer-samples.yml
      - packages/zowe-explorer-api/**
      - samples/**
  pull_request:
    paths:
      - .github/workflows/zowe-explorer-samples.yml
      - packages/zowe-explorer-api/**
      - samples/**

jobs:
  samples-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: node-${{ matrix.node-version }}-ze-samples-ci-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      # Continue to run tests on the other systems if one fails
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # install yarn
      - run: npm install -g yarn

      - run: yarn config set network-timeout 60000 && yarn install --frozen-lockfile

      - run: for dir in samples/*; do pushd $dir && yarn && yarn run compile && popd; done
        shell: bash
